### ISSUE TITLE
ERROR: Service 'calendso' failed to build

### ISSUE THREAD

**Issue by drwb** [calendso/docker#42]
A `docker-compose up --build` command on a fresh pull produces:

info  - Skipping validation of types...
info  - Creating an optimized production build...
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/app/node_modules/next/dist/build/swc/index.js:29:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
error - Failed to load SWC binary, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Service 'calendso' failed to build: The command '/bin/sh -c yarn build && yarn install --production --ignore-scripts --prefer-offline' returned a non-zero code: 1

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:08 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by TheBestMoshe** [comment]
As a temporary fix, I was able to get it to build by using one of the suggestions provided in the [help url](https://nextjs.org/docs/messages/failed-loading-swc). I created a `.babelrc` file and added the following content to it:
```
{
    "presets": ["next/babel"]
 }
```

**Comment by TheBestMoshe** [comment]
It seems like #41 fixes this.

**Comment by drwb** [comment]
Yes, manually making that change removed this error.
