### ISSUE TITLE
docker is not picking env file on runtime

### ISSUE THREAD

**Issue by juggernaut451** [calendso/docker#43]
env varriable like smtp setting & zoom credentials are not setting up

**Comment by krumware** [comment]
Currently, this is a limitation in the calendso main project side with next.js. those environmental variables are injected at build time but not at runtime (and is being addressed in other WIP branches).

If you choose to in the meantime, they can be used at runtime by modifying start.sh to use `yarn dev` instead of `yard start`, or by specifying `yarn dev` as the docker run command (but you'll lose the database liveness check)

**Comment by krumware** [comment]
to clarify, I want to keep this issue open so that it gets addressed in some fashion

**Comment by wivaku** [comment]
I have modified `start.sh` and replaced `yarn start` with `yarn dev`. 
The log now shows:
```
calendso     | + yarn dev
calendso     | yarn run v1.22.15
calendso     | $ next dev
calendso     | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
calendso     | Error: > Couldn't find a `pages` directory. Please create one under the project root
calendso     |     at Object.findPagesDir (/app/node_modules/next/dist/lib/find-pages-dir.js:33:11)
calendso     |     at new DevServer (/app/node_modules/next/dist/server/dev/next-dev-server.js:111:44)
calendso     |     at NextServer.createServer (/app/node_modules/next/dist/server/next.js:102:20)
calendso     |     at /app/node_modules/next/dist/server/next.js:117:42
calendso     |     at async NextServer.prepare (/app/node_modules/next/dist/server/next.js:92:24)
calendso     |     at async /app/node_modules/next/dist/cli/next-dev.js:128:9
calendso     | error Command failed with exit code 1.
```

**Comment by PeerRich** [comment]
@bvallelunga any ideas?

**Comment by krumware** [comment]
please test with https://github.com/calendso/docker/pull/51 if possible

**Comment by krumware** [comment]
please re-test with current files

**Comment by krumware** [comment]
Closing for inactivity
