### ISSUE TITLE
Error: Invalid key length - Apple Calendar Integration

### ISSUE THREAD

**Issue by davidwuest** [calendso/docker#75]
When trying to add the apple calendar I get the following error. Any ideas?
Error: Invalid key length
at Cipheriv.createCipherBase (internal/crypto/cipher.js:103:19)
at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)
at new Cipheriv (internal/crypto/cipher.js:227:22)
at Object.createCipheriv (crypto.js:124:10)
at symmetricEncrypt (/app/.next/server/chunks/1027.js:29:66)
at handler (/app/.next/server/pages/api/integrations/apple/add.js:145:88)
at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils.js:102:9)
at async Server.handleApiRequest (/app/node_modules/next/dist/server/next-server.js:1064:9)
at async Object.fn (/app/node_modules/next/dist/server/next-server.js:951:37)
at async Router.execute (/app/node_modules/next/dist/server/router.js:222:32)

**Comment by adriaanvanrossum** [comment]
Shouldn't that `CALENDSO_ENCRYPTION_KEY` not be 32 characters?

**Comment by davidwuest** [comment]
https://github.com/calcom/cal.com/issues/1585
